apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: taskapp
type: Opaque
stringData:
  DATABASE_USER: "REPLACE_ME_locally_never_commit"
  DATABASE_PASSWORD: "REPLACE_ME_locally_never_commit"
  SECRET_KEY: "REPLACE_ME_locally_never_commit"