[server]

control_plane ansible_host=3.95.240.159 private_ip=10.0.1.180

[agents]

worker_0 ansible_host=34.230.28.98 private_ip=10.0.1.100

worker_1 ansible_host=32.192.48.63 private_ip=10.0.1.246

[k3s_cluster:children]

server
agents